(() => {
  'use strict';
  const E=window.Evolution,A=window.EvolutionArt,M=window.MicroUI,X=window.ExpeditionUI,$=s=>document.querySelector(s),ui=$('#ui'),canvas=$('#world'),art=new A.Renderer(canvas);
  const SAVE='world-eater.v2.save',PREF='world-eater.v2.settings',CODEX='world-eater.v4.codex';let state='menu',world=null,saved=null,settings={sound:true},clock=0,last=performance.now(),hudTime=0,saveTime=0,toastTimer,pendingLevel=0,lastForm=-1;
  const keys=new Set();let joystick={x:0,y:0},pointer=null,dragOrigin=null,isDragging=false,touchUsed=matchMedia('(pointer:coarse)').matches;
  function read(key){try{return JSON.parse(localStorage.getItem(key));}catch{return null;}}
  function write(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{return false;}}
  const profile=E.readProfile(read(CODEX));let journalTab='mutations',inheritedEgg=profile.companions[0]||null;
  const raw=read(SAVE);if(E.validSave(raw))saved=raw;const pref=read(PREF);if(typeof pref?.sound==='boolean')settings.sound=pref.sound;
  function save(){if(!world)return;E.remember(profile,world.save);write(CODEX,profile);saved=JSON.parse(JSON.stringify(world.save));if(!write(SAVE,saved)&&!save.warned){save.warned=true;notify('Браузер запретил сохранение. Прогресс сохранится только до закрытия вкладки.');}}
  const n=value=>Math.floor(value).toLocaleString('ru-RU');
  function short(value){return value>=1e6?(value/1e6).toFixed(1)+'м':value>=10000?(value/1000).toFixed(1)+'к':n(value);}
  function sizeText(r){const meters=r*.02;return meters<1?Math.round(meters*100)+' см':meters<1000?meters.toFixed(meters<10?1:0)+' м':meters<1e6?(meters/1000).toFixed(meters<10000?1:0)+' км':n(meters/1000)+' км';}
  function notify(message){$('#notifications').textContent=message;$('#notifications').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#notifications').classList.remove('show'),3200);}
  const arrow='<svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 12h15m-6-6 6 6-6 6"/></svg>';
  const diamond='<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.5"><path d="m12 2 8 7-8 13L4 9zM4 9h16m-8-7-3 7 3 13 3-13z"/></svg>';
  const pauseIcon='<svg width="15" height="15" viewBox="0 0 20 20" fill="currentColor"><path d="M5 3h3v14H5zm7 0h3v14h-3z"/></svg>';
  const bookIcon='<svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M3 4q5-1 9 2 4-3 9-2v15q-5-1-9 2-4-3-9-2zM12 6v15M6 8h3m-3 4h3m6-4h3m-3 4h3"/></svg>';
  const fullscreenIcon='<svg width="16" height="16" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M7 3H3v4m10-4h4v4M3 13v4h4m10-4v4h-4"/></svg>';
  function soundIcon(){return `<svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M4 9h4l5-4v14l-5-4H4z"/>${settings.sound?'<path d="M17 8q4 4 0 8m3-11q7 7 0 14"/>':'<path d="m17 9 5 6m0-6-5 6"/>'}</svg>`;}
  function skillIcon(id){const paths={dash:'M3 12h13m-5-6 6 6-6 6M3 7h5m-5 10h5m10-14 5 9-5 9',nova:'M12 2v4m0 12v4M2 12h4m12 0h4M5 5l3 3m8 8 3 3M5 19l3-3m8-8 3-3',storm:'m14 2-9 12h7l-2 8 9-13h-7z',devour:'M20 8a9 9 0 1 0 1 7M17 7a6 6 0 1 0 1 8M15 10a3 3 0 1 0 0 4'};return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[id]}"/>${id==='nova'?'<circle cx="12" cy="12" r="3"/>':''}</svg>`;}
  class AudioEngine{
    constructor(){this.ctx=null;this.limits={};this.music=0;this.step=0;}
    unlock(){try{if(!this.ctx){this.ctx=new(window.AudioContext||window.webkitAudioContext)();this.gain=this.ctx.createGain();this.gain.gain.value=.18;this.gain.connect(this.ctx.destination);}if(this.ctx.state==='suspended')this.ctx.resume();}catch{}}
    tone(f,d=.15,type='sine',v=.3,end){if(!settings.sound||!this.ctx||this.ctx.state!=='running')return;const t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(f,t);if(end)o.frequency.exponentialRampToValueAtTime(Math.max(15,end),t+d);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(Math.max(.002,v),t+.008);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g);g.connect(this.gain);o.start(t);o.stop(t+d+.02);o.onended=()=>{o.disconnect();g.disconnect();};}
    noise(d=.1,v=.2,f=1800){if(!settings.sound||!this.ctx||this.ctx.state!=='running')return;const ctx=this.ctx,buffer=ctx.createBuffer(1,Math.ceil(ctx.sampleRate*d),ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(1-i/data.length);const source=ctx.createBufferSource(),gain=ctx.createGain(),filter=ctx.createBiquadFilter();source.buffer=buffer;filter.type='lowpass';filter.frequency.value=f;gain.gain.value=v;source.connect(filter);filter.connect(gain);gain.connect(this.gain);source.start();source.onended=()=>{source.disconnect();filter.disconnect();gain.disconnect();};}
    play(type){if(!settings.sound||!this.ctx)return;const t=this.ctx.currentTime,interval={hit:.12,eat:.12,level:.25}[type]||.15;if(t-(this.limits[type]??-10)<interval)return;this.limits[type]=t;
      if(type==='click')this.tone(430,.085,'sine',.22,610);
      else if(type==='hit'){this.noise(.065,.25,2300);this.tone(180,.07,'triangle',.3,90);}
      else if(type==='eat'){this.tone(380,.14,'sine',.38,850);setTimeout(()=>this.tone(1050,.14,'sine',.16),60);}
      else if(type==='level'){this.tone(523,.16,'triangle',.3);setTimeout(()=>this.tone(784,.25,'sine',.35),70);}
      else if(type==='evolve'||type==='pet'||type==='won'){[262,330,392,523,784].forEach((f,i)=>setTimeout(()=>this.tone(f,.65,'sine',.3),i*95));}
      else if(type==='hurt'){this.tone(105,.18,'triangle',.42,48);this.noise(.15,.3,900);}
      else if(type==='dash')this.tone(140,.26,'triangle',.4,700);
      else if(type==='nova'){this.noise(.35,.4,1700);this.tone(90,.45,'sine',.5,220);}
      else if(type==='storm'){this.noise(.35,.4,3100);this.tone(600,.4,'triangle',.25,100);}
      else if(type==='devour')this.tone(330,.8,'sine',.4,55);
      else if(type==='dead')this.tone(250,.7,'triangle',.3,45);
    }
    update(dt){if(state!=='playing'||!settings.sound)return;this.music-=dt;if(this.music>0)return;this.music=.5;this.step++;const notes=[130.81,164.81,196,220,196,164.81,146.83,196];if(this.step%2===0)this.tone(notes[(this.step/2)%8],.9,'sine',.035);if(this.step%4===0)this.tone(notes[(this.step/4)%8]*2,.85,'sine',.045);if(this.step%16===0)this.tone(65.4,1.8,'sine',.07);}
  }
  const audio=new AudioEngine();
  function topbar(){return `<header class="topbar"><div class="brand"><span class="brand-icon">✦</span> ПОЖИРАТЕЛЬ МИРОВ</div><div class="top-actions"><span class="eyebrow muted" style="font-size:8px;margin-right:10px">МИР, ИЗ КОТОРОГО МОЖНО ВЫРАСТИ</span><button class="icon-button" data-action="sound" aria-label="${settings.sound?'Выключить':'Включить'} звук">${soundIcon()}</button><button class="icon-button" data-action="fullscreen" aria-label="Полный экран">${fullscreenIcon}</button></div></header>`;}
  function menu(){art.previewHero=saved?.hero||selectedHero||'dragon';art.previewStage=2;state='menu';world=null;keys.clear();$('#touch').hidden=true;ui.innerHTML=`<section class="screen menu">${topbar()}<main class="menu-main"><div class="hero-copy"><div class="eyebrow">МОЛЕКУЛА. МИКРОБ. ХИЩНИК. ЛЕГЕНДА.</div><h1>ПОЖИРАТЕЛЬ<br><span>МИРОВ</span></h1><p class="lead">Сегодня ты — молекула в капле.<br>Завтра — больше своего мира.</p><p class="description">Начни жизнь в красивом микромире.<br>Поглощай. Меняй форму. Открой свою стихию.<br>Смотри, как огромный мир становится маленьким.</p><div class="button-row">${saved&&!saved.won?`<button class="primary" data-action="continue">Продолжить · ${saved.phase==='micro'?'μ':'ур.'} ${n(saved.level)} ${arrow}</button><button class="icon-button" style="height:52px;width:45px" data-action="restart" title="Выбрать другого героя" aria-label="Выбрать другого героя">↻</button>`:`<button class="primary" data-action="new">${saved?.won?'Новая вселенная':'Выбрать героя'} ${arrow}</button>`}<button class="icon-button" style="height:52px;width:45px" data-action="help" aria-label="Как играть">?</button></div><div class="menu-meta"><span><b>10 000</b>УРОВНЕЙ РОСТА</span><span><b>4</b>УНИКАЛЬНЫХ ГЕРОЯ</span><span><b>18</b>БОЕВЫХ МУТАЦИЙ</span></div><p class="expedition-release">НОВОЕ · От укрытия под листом до поглощения родного пруда. Мутации, яйца и память мира.<br>Прокачка ускорена · прогресс сохраняется.</p><button class="atlas-menu-link" data-action="journal" data-tab="discoveries">${A.dnaIcon('book')} Атлас открытий · память прошлых жизней ↗</button></div></main><div class="specimen-label"><strong>НЕ СУДИ ПО РАЗМЕРУ.</strong><span>У ЭТОГО МАЛЫША БОЛЬШОЕ БУДУЩЕЕ.</span></div><footer class="menu-footer"><div class="keys"><span><kbd>W A S D</kbd> движение</span><span>или <kbd>КЛИК</kbd> по добыче</span><span>рост прямо в бою</span></div><span class="eyebrow muted" style="font-size:8px">БЕЗ РЕКЛАМЫ · БЕЗ ОЖИДАНИЯ ЭНЕРГИИ</span></footer></section>`;}

  let selectedHero=saved?.hero||'dragon',pendingAscensions=0;
  function chooseHero(ascensions=0){if(world)save();inheritedEgg=profile.companions.includes(inheritedEgg)?inheritedEgg:profile.companions[0]||null;pendingAscensions=ascensions;state='select';world=null;keys.clear();$('#touch').hidden=true;art.previewHero=selectedHero;art.previewStage=2;drawPicker();}
  function drawPicker(){const h=E.hero(selectedHero);document.documentElement.style.setProperty('--hero-color',h.color);art.previewHero=h.id;ui.innerHTML=`<section class="screen picker scrollable">${topbar()}<main class="picker-main"><div class="picker-copy"><div class="eyebrow">ЧЕТЫРЕ ГЕРОЯ. ЧЕТЫРЕ ПУТИ ЭВОЛЮЦИИ.</div><h1>Кем ты станешь?</h1><div class="hero-options">${E.HEROES.map(q=>`<button class="hero-option ${q.id===h.id?'selected':''}" data-action="pick-hero" data-hero="${q.id}" aria-label="Выбрать героя: ${q.name}" aria-pressed="${q.id===h.id}"><span class="hero-option-art">${A.heroPortrait({hero:q.id,level:1})}</span><strong>${q.short}</strong><small>${q.element}</small></button>`).join('')}</div><div class="hero-summary"><h2>${h.name}</h2><span>${h.role}</span><p>${h.description}</p></div><div class="micro-picker-route">${A.microIcon("molecule")}<b>Молекула</b><span>→</span>${A.microIcon("cell")}<b>Клетка</b><span>→</span>${A.microIcon("microbe")}<b>Микроб</b><span>→ герой</span></div><div class="hero-skill-grid">${h.skills.map(sk=>`<div class="hero-skill"><span class="skill-symbol">${A.skillIcon(sk)}</span><div><strong>${sk.name} <kbd>${sk.key==='ПРОБЕЛ'?'SPACE':sk.key}</kbd></strong><p>${sk.description}</p><small>${sk.level===1?'С первого уровня':'Уровень '+sk.level} · ${sk.cooldown} сек.</small></div></div>`).join('')}</div>${X.heritage(profile,inheritedEgg)}<div class="button-row picker-actions"><button class="primary" data-action="launch-hero">Начать за ${h.short==='Бездна'?'пожирателя':h.short==='Лис'?'лиса':h.short==='Титан'?'титана':'дракона'} ${arrow}</button><button class="secondary" data-action="menu">Назад</button></div></div><div class="preview-caption"><span>${h.element}</span><strong>От малыша до легенды</strong><button class="secondary" data-action="preview-stage">${art.previewStage===0?'Показать взрослую форму':'Показать малыша'}</button></div></main><footer class="picker-footer">Твой путь начнётся с молекулы: μ1–μ100 в микромире, затем уровни 1–10 000 в большом мире. Выбранная стихия останется с тобой.</footer></section>`;}

  function start(data){E.prepareAdventure(data);world=data.phase==='micro'?new E.MicroWorld(data):new E.World(data);E.prepareHabitat(data);E.ensureNests(world);E.ensureHabitat(world);document.documentElement.style.setProperty('--hero-color',E.hero(data).color);art.lastRealm=-1;lastForm=E.formIndex(data.level);state='playing';keys.clear();joystick={x:0,y:0};art.reset(world);hud();save();processProgress();}
  function hud(){if(!world)return;if(world.isMicro){ui.innerHTML=M.hud(world,{pause:pauseIcon});M.update(world);X.mount(world);$('#touch').hidden=state!=='playing'||!(touchUsed||innerWidth<=700);return;}const s=world.save,f=E.formFor(s),realm=E.REALMS[f.realm];ui.innerHTML=`<div class="hud ${f.realm>=4?'cosmic':''}"><div class="hud-top"><div class="hero-panel"><div class="hero-panel-top"><div class="portrait" id="hero-portrait">${A.heroPortrait(s)}</div><div><div class="hero-level"><span id="level">${n(s.level)}</span><small>/ 10 000</small></div><div class="hero-form" id="form-name">${f.name}</div></div></div><div class="hp-track"><i id="hp-fill"></i></div><div class="xp-track"><i id="xp-fill"></i></div><div class="panel-tiny"><span id="xp-label"></span><span id="hp-label"></span></div></div><div class="realm-title"><span id="realm-sub">${realm.sub}</span><strong id="realm-name">${realm.name}</strong></div><div class="hud-tools"><div class="essence">${diamond}<span id="essence">${short(s.essence)}</span></div><button class="icon-button" data-action="hunt" aria-label="Выбрать ближайшую добычу" title="Ближайшая добыча · Z">◎</button><button class="icon-button" data-action="collection" aria-label="Питомцы и эволюции" title="Питомцы и эволюции · Tab">${bookIcon}</button><button class="icon-button" data-action="pause" aria-label="Пауза" title="Пауза · Esc">${pauseIcon}</button></div></div><aside class="hud-middle"><div class="goal-card"><div class="eyebrow">СЛЕДУЮЩЕЕ ПРЕВРАЩЕНИЕ</div><h3 id="goal-title"></h3><p id="goal-description"></p><div class="mini-progress"><i id="goal-progress"></i></div><div class="next-pet" id="next-pet"></div></div><div class="world-progress">${E.REALMS.map((r,i)=>`<div class="world-step ${i===f.realm?'current':i<f.realm?'done':''}"><i></i><span>${r.name.toUpperCase()}</span></div>`).join('')}</div></aside><div class="scale-indicator">ТВОЙ РАЗМЕР <b id="size"></b></div><div class="combo" id="combo" hidden></div><div class="hud-bottom"><div class="pet-dock"><div class="between"><span class="eyebrow">ТВОЯ СТАЯ</span><span class="eyebrow" id="pet-count">${s.activePets.length}/3</span></div><div class="pet-slots" id="pet-slots"></div></div><div class="abilities">${E.skillsFor(world?.save||selectedHero).map(skill=>`<button class="ability ${s.level<skill.level?'locked':''}" data-action="skill" data-skill="${skill.id}" aria-label="${skill.name}" title="${s.level<skill.level?'Откроется на уровне '+skill.level:skill.description+' · '+skill.key}">${A.skillIcon(skill)}<span class="name">${skill.name}</span><span class="key">${s.level<skill.level?'УР. '+skill.level:skill.key}</span><span class="cooldown" id="cd-${skill.id}" hidden></span></button>`).join('')}</div><div class="target-card" id="target-card"></div></div><div class="hint-banner" id="hint"></div></div>`;X.mount(world);updateHUD();$('#touch').hidden=state!=='playing'||!(touchUsed||innerWidth<=700);}
  function updateHUD(){if(!world||!$('#level'))return;X.update(world);if(world.isMicro){M.update(world);return;}const s=world.save,p=world.player,index=E.formIndex(s.level),f=E.formFor(s,index),next=index<11?E.formFor(s,index+1):null,st=E.stats(s);
    $('#level').textContent=n(s.level);$('#hp-fill').style.width=E.clamp(p.hp/st.hp*100,0,100)+'%';$('#hp-fill').style.background=p.hp/st.hp<.3?'#d28a70':'#78bfa0';$('#xp-fill').style.width=s.level===10000?'100%':s.xp/E.xpNeeded(s.level)*100+'%';$('#xp-label').textContent=s.level===10000?'МАКСИМАЛЬНАЯ ЭВОЛЮЦИЯ':short(s.xp)+' / '+short(E.xpNeeded(s.level))+' XP';$('#hp-label').textContent=n(p.hp)+' HP'+(p.shield>0?' +'+n(p.shield)+' ЩИТ':'');$('#essence').textContent=short(s.essence);$('#size').textContent=sizeText(p.r);
    $('#goal-title').textContent=next?next.name:'Сердце вселенной';$('#goal-description').textContent=next?'Уровень '+n(next.level)+' · осталось '+n(next.level-s.level):'Победи последнего стража и начни новую вселенную.';$('#goal-progress').style.width=(next?(s.level-f.level)/(next.level-f.level)*100:100)+'%';
    const pet=E.PETS.find(q=>!s.pets.includes(q.id));$('#next-pet').innerHTML=pet?A.portrait(pet.body,pet.color)+`<span>${pet.name}<br>Питомец на ур. ${n(pet.level)}</span>`:'✦ Все спутники найдены';
    $('#pet-slots').innerHTML=Array.from({length:3},(_,i)=>{const id=s.activePets[i],q=E.PETS.find(q=>q.id===id);return `<button class="pet-slot ${q?'filled':''}" data-action="collection" aria-label="${q?q.name+' — питомцы':'Открыть питомцев'}" title="${q?q.name+' · уровень '+s.level:'Новый питомец откроется на уровне '+(pet?.level||10000)}">${q?A.portrait(q.body,q.color,s.level)+`<small>${s.level>=q.level*8?'★★':'★'}</small>`:'+'}</button>`;}).join('');$('#pet-count').textContent=s.activePets.length+'/3';
    for(const skill of E.skillsFor(world?.save||selectedHero)){const button=$(`[data-skill="${skill.id}"]`),locked=s.level<skill.level;button.classList.toggle('locked',locked);button.querySelector('.key').textContent=locked?'УР. '+skill.level:skill.key;const cd=$('#cd-'+skill.id);cd.hidden=world.cooldowns[skill.id]<=0;cd.textContent=world.cooldowns[skill.id].toFixed(1);}
    const target=world.enemies.find(e=>e.id===world.targetId)||world.nearest(p.x,p.y,p.r*6);const card=$('#target-card');if(target){const strong=target.level>s.level*1.55;card.classList.toggle('danger',strong);card.innerHTML=`<div class="eyebrow">${target.boss?'СТРАЖ МИРА':'БЛИЖАЙШАЯ ДОБЫЧА'} · УР. ${n(target.level)}</div><strong>${target.name}</strong><div class="hp-track"><i style="width:${target.hp/target.maxHp*100}%;background:${strong?'#d68f78':'#88b89a'}"></i></div><span class="target-hint">${strong?'Опасен. Сначала вырасти.':target.level<s.level*.35?'Теперь можно поглотить на бегу.':'Подойди ближе, чтобы атаковать.'}</span>`;}else{card.classList.remove('danger');card.innerHTML='<div class="eyebrow">ОХОТА ПРОДОЛЖАЕТСЯ</div><strong>Мир становится меньше.</strong><span class="target-hint">Ищи существ с зелёными уровнями.</span>';}
    const hint=$('#hint');hint.hidden=s.kills>16;hint.innerHTML=s.kills<3?'<b>Z — ближайшая добыча.</b> Или кликни по существу / двигайся на WASD':s.level<5?'С каждым поглощением ты растёшь. <b>Питомец откроется на уровне 10.</b>':s.level<30?'<b>Q — твоя первая стихия.</b> Испытай её на ближайшей добыче.':'<b>E — новая способность.</b> У каждого героя свои приёмы.';
    const combo=$('#combo');combo.hidden=world.combo<3;combo.innerHTML='×'+world.combo+'<small>ЦЕПОЧКА ПОГЛОЩЕНИЙ</small>';
  }
  function levelPop(amount){pendingLevel+=amount;const el=$('#level-burst');el.classList.remove('pop');void el.offsetWidth;el.innerHTML=(world.isMicro?'МИКРОУРОВЕНЬ μ':'УРОВЕНЬ ')+n(world.save.level)+`<small>${pendingLevel>1?'+'+n(pendingLevel)+' УРОВНЕЙ':'ТЫ СТАЛ СИЛЬНЕЕ'}</small>`;el.classList.add('pop');clearTimeout(levelPop.timer);levelPop.timer=setTimeout(()=>{pendingLevel=0;},800);}
  function modal(html,cls=''){ui.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="modal"><section class="modal ${cls}" role="dialog" aria-modal="true" aria-label="${state==='evolution'?'Новая эволюция':'Меню игры'}">${html}</section></div>`);$('#touch').hidden=true;keys.clear();joystick={x:0,y:0};pointer=null;world&&(world.player.vx=world.player.vy=0);requestAnimationFrame(()=>$('#modal button')?.focus());}
  function closeModal(){ $('#modal')?.remove();state='playing';keys.clear();hud();processProgress();}
  function evolution(){if(world.isMicro){state='evolution';hud();modal(M.evolution(world),'evolution-modal micro-evolution');audio.play('evolve');save();return;}state='evolution';const s=world.save,f=E.formFor(s),previous=E.FORMS[Math.max(0,E.formIndex(s.level)-1)],amount=s.choices;hud();modal(`<div class="evo-heading">НОВАЯ ФОРМА · УРОВЕНЬ ${n(s.level)}</div><div class="evo-preview">${A.heroPortrait(s)}</div><h2>${f.name}</h2><p>${f.description}</p><div class="evo-bonuses"><span>↗ Размер ${sizeText(world.player.r)}</span><span>♥ Прочность восстановлена</span><span>✦ ${amount>1?amount+' усиления':'Выбери усиление'}</span></div><div class="traits"><button class="trait" data-action="trait" data-trait="power"><span class="symbol">✹</span><strong>Путь хищника</strong><p>+${16*amount}% к силе атак героя и всех питомцев.</p><span class="choose">СТАТЬ СИЛЬНЕЕ <span>↗</span></span></button><button class="trait" data-action="trait" data-trait="growth"><span class="symbol">✦</span><strong>Вечный голод</strong><p>+${15*amount}% опыта от каждой добычи. Расти ещё быстрее.</p><span class="choose">РАСТИ БЫСТРЕЕ <span>↗</span></span></button><button class="trait" data-action="trait" data-trait="vitality"><span class="symbol">♡</span><strong>Несокрушимый</strong><p>+${20*amount}% максимальной прочности. Охоться смелее.</p><span class="choose">ЖИТЬ ДОЛЬШЕ <span>↗</span></span></button></div>`,'evolution-modal');audio.play('evolve');save();}
  function petReveal(){const id=world.pendingPets.shift(),pet=E.PETS.find(q=>q.id===id);if(!pet)return;state='pet';hud();modal(`<div class="eyebrow">У ТЕБЯ НОВЫЙ СПУТНИК</div><div class="evo-preview">${A.portrait(pet.body,pet.color,world.save.level)}</div><h2>Знакомься, ${pet.name}.</h2><p><b>${pet.role}.</b> ${pet.description}</p><p>${world.save.activePets.includes(id)?'Уже в твоей стае. Питомец сражается сам и растёт вместе с тобой.':'Он ждёт в коллекции. Освободи одно из трёх мест, чтобы взять его с собой.'}</p><button class="primary" data-action="pet-done">${world.save.activePets.includes(id)?'Вместе мы сильнее':'Отлично, идём дальше'} ${arrow}</button>`,'pet-reveal');audio.play('pet');save();}
  function mutationChoice(){state='mutation';hud();modal(X.choice(world),'dna-modal scrollable');audio.play('evolve');save();}
  function journal(tab=journalTab){if(!['playing','menu','journal'].includes(state))return;if(world)save();journalTab=tab;$('#modal')?.remove();state='journal';modal(X.journal(world,profile,tab),'atlas-modal scrollable');}
  function closeJournal(){world?closeAndResume():menu();}
  function processProgress(){if(!world||!['playing','evolution','pet'].includes(state))return;if(world.status==='dead'){dead();return;}if(world.status==='emerging'){state='birth';hud();modal(M.birth(world),'birth-modal');audio.play('evolve');save();return;}if(world.status==='won'){win();return;}if(world.save.choices>0){if(state!=='evolution')evolution();return;}if(world.save.adventure.pending&&state==='playing'){mutationChoice();return;}if(world.pendingPets.length&&state==='playing'){petReveal();return;}}
  function pause(){if(state!=='playing')return;state='pause';save();modal(`<div class="eyebrow">МАЛЕНЬКАЯ ПЕРЕДЫШКА</div><h2>Вселенная подождёт.</h2><p>Уровень ${world.isMicro?"μ":""}${n(world.save.level)}, эволюции и питомцы сохранены. Можно продолжить развитие.</p><button class="primary" data-action="resume">Продолжить охоту ${arrow}</button><button class="secondary" data-action="sound">${settings.sound?'Выключить':'Включить'} звук</button><button class="secondary" data-action="fullscreen">Полный экран</button><button class="secondary" data-action="menu">Сохранить и выйти</button>`);}
  function collection(){if(!world||state!=='playing')return;if(world.isMicro){state='collection';save();modal(M.collection(world),'collection scrollable micro-collection');return;}state='collection';save();const s=world.save;modal(`<div class="collection-header"><div><div class="eyebrow">ТВОЯ ИСТОРИЯ ЭВОЛЮЦИИ</div><h2>Вместе — больше.</h2></div><button class="icon-button" data-action="close-collection" aria-label="Закрыть коллекцию">✕</button></div><p class="collection-sub">Выбери до трёх спутников. Чтобы заменить питомца, сначала отправь одного из активных в запас.</p>${s.microComplete?`<div class="origin-memory">${A.microIcon("dna")}<span><b>Искра жизни · +10% опыта</b><small>Молекула → клетка → микроб → колония → герой. Твой микромир пройден.</small></span></div>`:""}<div class="collection-pets">${E.PETS.map(p=>{const unlocked=s.pets.includes(p.id),active=s.activePets.includes(p.id);return `<div class="collection-pet ${unlocked?'':'locked'}">${A.portrait(p.body,p.color,s.level)}<strong>${p.name}</strong><p>${p.role}<br>${unlocked?'Уровень '+n(s.level):'Откроется на ур. '+n(p.level)}</p><button class="${active?'primary':'secondary'}" data-action="toggle-pet" data-pet="${p.id}" ${unlocked?'':'disabled'}>${active?'В СТАЕ ✓':unlocked?'ВЗЯТЬ С СОБОЙ':'ЕЩЁ НЕ НАЙДЕН'}</button></div>`;}).join('')}</div><div class="evo-road">${E.FORMS.map((_,i)=>E.formFor(s,i)).map((f,i)=>`<div class="road-card ${s.level>=f.level?'done':''} ${i===E.formIndex(s.level)?'current':''}">${A.heroPortrait(s,i)}<small>${f.name}</small><b>УР. ${n(f.level)}</b></div>`).join('')}</div><p class="collection-sub" style="margin-top:22px;margin-bottom:0!important">Путь хищника: +${s.traits.power*16}% атаки · Вечный голод: +${s.traits.growth*15}% опыта · Несокрушимый: +${s.traits.vitality*20}% здоровья</p>`,'collection scrollable');}
  function dead(){state='dead';save();modal(`<div class="eyebrow">НА ЭТОТ РАЗ ДОБЫЧА ОКАЗАЛАСЬ СИЛЬНЕЕ</div><h2>Ты ещё вырастешь.</h2><p>Твой ${world.isMicro?"μ":""}${n(world.save.level)} уровень, форма и питомцы сохранены. Охоться на зелёные цели и избегай красных зон стражей.</p><button class="primary" data-action="revive">Возродиться ${arrow}</button><button class="secondary" data-action="menu">В главное меню</button>`);audio.play('dead');}
  function win(){state='won';save();const s=world.save;modal(`<div class="eyebrow">10 000 УРОВНЕЙ. ОДНА НЕВЕРОЯТНАЯ ЖИЗНЬ.</div><div class="evo-preview">${A.portrait('cosmic','#fff0ad')}</div><h2>Теперь ты — целая вселенная.</h2><p>Когда-то ты прятался в траве. Теперь даже родная планета помещается рядом с тобой.</p><div class="result-stats"><div><b>${n(s.level)}</b><small>УРОВЕНЬ</small></div><div><b>${n(s.kills)}</b><small>ПОГЛОЩЕНО</small></div><div><b>${Math.round(s.time/60)}</b><small>МИНУТ РОСТА</small></div></div><p>Следующая жизнь начнётся с молекулы. После рождения в большом мире ты получишь бонус к опыту +${Math.min(s.ascensions+1,5)*20}%.</p><button class="primary" data-action="ascend">Начать новую вселенную ${arrow}</button><button class="secondary" data-action="menu">Пока остаться здесь</button>`,'pet-reveal');audio.play('won');}
  function help(){if(world?.isMicro||!world&&(!saved||saved.phase==='micro')){state='help';modal(M.help(world||{save:saved||E.newJourney(0,selectedHero)}),'micro-evolution');return;}state='help';modal('<div class="eyebrow">КАК ВЫРАСТИ ИЗ СВОЕГО МИРА</div><h2>Охоться. Расти. Меняй мир.</h2><p><b>WASD / стрелки</b> — движение. <b>Z</b> — выбрать ближайшую посильную добычу. Можно кликнуть по существу: герой подойдёт и атакует.</p><p><b>Пробел</b> — особый рывок с первого уровня.<br><b>Q</b> — первая стихия с ур. 5.<br><b>E</b> — вторая способность с ур. 30.<br><b>R</b> — высшая способность с ур. 80.</p><p>У всех четырёх героев разные приёмы. Зелёные уровни — посильная добыча, красные — опасные враги. Уходи из красных зон боссов.</p><p><b>C</b> — геном, яйца и открытия. <b>G</b> — гнездо хранителя. <b>V</b> — родной мир.<br><b>Tab</b> — питомцы и формы. <b>Esc</b> — пауза.<br>Прокачка до 10 000, первый питомец на ур. 10. На телефоне доступны джойстик и кнопки.</p><button class="primary" data-action="help-done">Понятно, идём дальше</button>');}
  function closeAndResume(){ $('#modal')?.remove();state='playing';hud();processProgress();}
  ui.addEventListener('click',async e=>{const button=e.target.closest('[data-action]');if(!button||button.disabled)return;audio.unlock();audio.play('click');const action=button.dataset.action;
    if(action==='new')chooseHero(saved?.won?saved.ascensions+1:0);
    else if(action==='inherit-egg'){if(profile.companions.includes(button.dataset.id)){inheritedEgg=button.dataset.id;drawPicker();}}
    else if(action==='pick-hero'){selectedHero=button.dataset.hero;drawPicker();}
    else if(action==='preview-stage'){art.previewStage=art.previewStage===0?2:0;drawPicker();}
    else if(action==='launch-hero'){if(saved)write(SAVE+'.backup',saved);const journey=E.newJourney(pendingAscensions,selectedHero);if(inheritedEgg)E.inheritEgg(journey,inheritedEgg,profile);start(journey);}
    else if(action==='emerge'){if(state==='birth'){const born=E.completeMicro(world.save);if(born){start(born);world.fx('solarRing',0,0,world.player.r*5,E.hero(born).color,1.5);notify('Ты родился! Искра жизни даёт +10% опыта. Люми появится на уровне 10.');}}}
    else if(action==='continue')start(JSON.parse(JSON.stringify(saved)));
    else if(action==='restart'){state='restart';modal('<div class="eyebrow">НОВАЯ ЖИЗНЬ</div><h2>Начать с маленького?</h2><p>Текущий заезд останется в резервной копии браузера. Новый начнётся с молекулы на микроуровне μ1.</p><button class="primary" data-action="confirm-new">Начать новый заезд</button><button class="secondary" data-action="cancel-new">Вернуться</button>');}
    else if(action==='confirm-new'){if(saved)write(SAVE+'.backup',saved);chooseHero(0);}
    else if(action==='cancel-new')menu();
    else if(action==='menu'){if(world)save();menu();}
    else if(action==='mutation-pick'){if(state==='mutation'&&E.chooseMutation(world,button.dataset.id)){save();closeAndResume();}}
    else if(action==='journal')journal(button.dataset.tab||'mutations');
    else if(action==='journal-tab')journal(button.dataset.tab);
    else if(action==='close-journal')closeJournal();
    else if(action==='hatch-egg'){const pet=E.hatchEgg(world,Number(button.dataset.id));if(pet){save();$('#modal')?.remove();state='hatch';modal(X.hatchReveal(pet),'pet-reveal');audio.play('pet');}}
    else if(action==='hatch-done'){closeAndResume();}
    else if(action==='rare-pet'){if(world&&E.activateCompanion(world,button.dataset.id==='none'?null:button.dataset.id)){save();journal('eggs');}}
    else if(action==='home-go'){if(state==='journal')closeJournal();if(state==='playing'&&E.seekHome(world)){notify('Возвращаемся к месту начала. Движение вручную отменяет путь.');updateHUD();}}
    else if(action==='seek-nest'){if(state==='journal')closeJournal();if(state==='playing'&&E.challengeNest(world)){notify('Путь к гнезду выбран. Движение вручную отменяет его.');updateHUD();}}
    else if(action==='hunt')hunt();else if(action==='pause')pause();else if(action==='resume')closeAndResume();
    else if(action==='trait'){if(world.evolve(button.dataset.trait)){save();closeAndResume();}}
    else if(action==='pet-done')closeAndResume();
    else if(action==='collection')collection();else if(action==='close-collection')closeAndResume();
    else if(action==='toggle-pet'){if(world.setPet(button.dataset.pet)){save();$('#modal').remove();state='playing';hud();collection();}else notify('В стае уже три спутника. Сначала отправь одного в запас.');}
    else if(action==='skill'){if(state!=='playing')return;const id=button.dataset.skill,skill=E.skillsFor(world?.save||selectedHero).find(s=>s.id===id);if(world.save.level<skill.level)notify(skill.name+' откроется на уровне '+n(skill.level));else if(world.useSkill(id)){audio.play(id);updateHUD();processProgress();}}
    else if(action==='revive'){start(JSON.parse(JSON.stringify(world.save)));}
    else if(action==='ascend'){chooseHero(world.save.ascensions+1);}
    else if(action==='help')help();else if(action==='help-done'){world?closeAndResume():menu();}
    else if(action==='sound'){settings.sound=!settings.sound;write(PREF,settings);if(state==='menu')menu();else if(state==='pause')button.textContent=settings.sound?'Выключить звук':'Включить звук';notify(settings.sound?'Звук включён':'Звук выключен');}
    else if(action==='fullscreen'){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{notify('Полный экран недоступен в этом окне.');}}
  });
  function hunt(){if(state!=='playing'||!world)return;world.nestGoal=null;world.habitatGoal=null;world.habitatChannel=null;const p=world.player,e=(world.isMicro&&world.save.level===100?world.enemies.find(q=>q.boss==='membrane'&&q.hp>0):null)||world.nearest(p.x,p.y,p.r*25,q=>q.level<=world.save.level*1.15);if(e){world.target(e.id);audio.play('click');}else notify('Подходящая добыча чуть дальше. Пройди вперёд.');}
  function pointerAction(event,forceMove=false){if(state!=='playing')return;world.nestGoal=null;world.habitatGoal=null;world.habitatChannel=null;const point=art.world(event.clientX,event.clientY);if(!forceMove){const hits=world.enemies.filter(e=>e.hp>0&&Math.hypot(e.x-point.x,e.y-point.y)<e.r*1.3).sort((a,b)=>Math.hypot(a.x-point.x,a.y-point.y)-Math.hypot(b.x-point.x,b.y-point.y));if(hits[0]){world.target(hits[0].id);return;}}world.targetId=null;world.autoHunt=false;world.moveTarget=point;}
  canvas.addEventListener('pointerdown',e=>{if(state!=='playing'||e.button>0)return;audio.unlock();pointer=e.pointerId;dragOrigin={x:e.clientX,y:e.clientY};isDragging=false;canvas.setPointerCapture(e.pointerId);pointerAction(e);e.preventDefault();});
  canvas.addEventListener('pointermove',e=>{if(pointer!==e.pointerId||state!=='playing')return;if(dragOrigin&&Math.hypot(e.clientX-dragOrigin.x,e.clientY-dragOrigin.y)>8)isDragging=true;if(isDragging)pointerAction(e,true);});
  canvas.addEventListener('pointerup',()=>{pointer=null;dragOrigin=null;isDragging=false;});canvas.addEventListener('pointercancel',()=>{pointer=null;});canvas.addEventListener('contextmenu',e=>e.preventDefault());
  document.addEventListener('keydown',e=>{if(e.repeat&&['Escape','Tab','KeyM','KeyF','KeyC','KeyG','KeyV'].includes(e.code))return;if(state==='playing'&&['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Tab'].includes(e.code))e.preventDefault();
    if(e.code==='Escape'){if(state==='journal'){closeJournal();return;}if(state==='playing')pause();else if(['pause','collection'].includes(state))closeAndResume();else if(state==='help')world?closeAndResume():menu();return;}
    if(e.code==='Tab'&&world&&['playing','collection'].includes(state)){e.preventDefault();state==='playing'?collection():closeAndResume();return;}
    if(e.code==='KeyC'&&['playing','journal','menu'].includes(state)){e.preventDefault();state==='journal'?closeJournal():journal();return;}
    if(e.code==='KeyV'&&state==='playing'){e.preventDefault();if(world.isMicro||E.homeObjective(world).id==='complete')journal('home');else if(E.seekHome(world))notify('К родному месту. Движение вручную отменяет путь.');return;}
    if(e.code==='KeyG'&&state==='playing'){e.preventDefault();if(E.challengeNest(world))notify('К гнезду. Уходи из красных зон хранителя.');return;}
    if(e.code==='KeyM'){settings.sound=!settings.sound;write(PREF,settings);audio.unlock();notify(settings.sound?'Звук включён':'Звук выключен');if(state==='menu')menu();}
    if(e.code==='KeyF'){if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});else document.documentElement.requestFullscreen().catch(()=>{});}
    if(state==='playing'){if(e.code==='KeyZ'&&!e.repeat)hunt();keys.add(e.code);const id={Space:'dash',KeyQ:'nova',KeyE:'storm',KeyR:'devour'}[e.code];if(id&&!e.repeat){audio.unlock();if(world.useSkill(id))audio.play(id);}}
    if($('#modal')&&e.code==='Tab'){const focus=[...$('#modal').querySelectorAll('button:not(:disabled)')],first=focus[0],last=focus[focus.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}
  });
  document.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();joystick={x:0,y:0};if(state==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing')pause();});window.addEventListener('pagehide',save);
  const stick=$('#stick');let stickId=null;function moveStick(e){const b=stick.getBoundingClientRect(),dx=e.clientX-b.left-b.width/2,dy=e.clientY-b.top-b.height/2,d=Math.hypot(dx,dy),m=35;joystick={x:dx/Math.max(d,m),y:dy/Math.max(d,m)};stick.firstElementChild.style.transform=`translate(${joystick.x*m}px,${joystick.y*m}px)`;}
  stick.addEventListener('pointerdown',e=>{stickId=e.pointerId;stick.setPointerCapture(e.pointerId);audio.unlock();moveStick(e);e.preventDefault();});stick.addEventListener('pointermove',e=>{if(e.pointerId===stickId)moveStick(e);});function resetStick(){stickId=null;joystick={x:0,y:0};stick.firstElementChild.style.transform='';}stick.addEventListener('pointerup',resetStick);stick.addEventListener('pointercancel',resetStick);stick.addEventListener('lostpointercapture',resetStick);
  window.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'){touchUsed=true;if(state==='playing')$('#touch').hidden=false;}});window.addEventListener('resize',()=>{art.resize();$('#touch').hidden=state!=='playing'||!(touchUsed||innerWidth<=700);});
  function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;clock+=dt;if(state==='playing'&&world){world.update(dt,{x:(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+joystick.x,y:(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0)+joystick.y});
      for(const event of world.events){if(event.type==='level'){audio.play('level');levelPop(event.amount);saveTime=4;}else if(event.type==='target'&&event.strong)notify('Он пока намного сильнее. Начни с существ с зелёными уровнями.');else if(event.type==='skill'){const skill=E.skillsFor(world?.save||selectedHero).find(s=>s.id===event.id);notify('Новая способность: '+skill.description+' · '+skill.key);hud();}else if(event.type==='bossDown')notify(event.name+' побеждён!');else if(event.type==='homeNotice')notify(event.message);else if(event.type==='homeMoment'){window.LivingUI.showMoment(event.id);audio.play('evolve');saveTime=4;}else if(event.type==='eggFound'){notify('Найдено: '+E.companion(event.kind).egg+'. Загляни в Атлас жизни · C.');saveTime=4;}else if(event.type==='eggReady'){notify(world.isMicro||world.save.level<10?'Яйцо выросло! Оно проснётся в большом мире с уровня 10.':'Питомец готов вылупиться! Открой Атлас жизни · C.');saveTime=4;}else if(event.type==='nestCleared'){notify(event.absorbed?'Ты вырос настолько, что поглотил гнездо целиком!':'Хранитель побеждён! Редкое яйцо уже в твоём атласе · C.');saveTime=4;}else if(event.type==='nestChallenge')notify('Хранитель пробудился. Уходи из красных зон!');else if(event.type==='nestSmall')notify('Здесь ты уже победил. Вырасти ещё, чтобы поглотить гнездо.');else if(['eat','hit','hurt'].includes(event.type))audio.play(event.type);}
      world.events.length=0;audio.update(dt);hudTime+=dt;saveTime+=dt;if(hudTime>.15){updateHUD();hudTime=0;}if(saveTime>3){save();saveTime=0;}processProgress();}
    art.draw(world,state,clock,dt);requestAnimationFrame(frame);
  }
  A.ready.then(()=>{if(state==='menu')menu();else if(state==='select')drawPicker();else if(state==='playing')hud();});
  if(location.hash==='#heroes'){chooseHero(saved?.won?saved.ascensions+1:0);try{history.replaceState(null,'',location.pathname+location.search);}catch{}}else menu();requestAnimationFrame(frame);
})();
