(() => {
'use strict';
const E=window.Evolution,A=window.EvolutionArt,$=s=>document.querySelector(s),fmt=n=>Math.floor(n).toLocaleString('ru-RU');
const tag=(icon,text)=>`<span class="dna-tag">${A.dnaIcon(icon)}${text}</span>`;
const bar=(v,max)=>`<div class="dna-progress"><i style="width:${Math.min(100,v/max*100)}%"></i></div>`;
const nextPoint=s=>(s.phase==='micro'?[8,40]:[5,35,180,900]).find(l=>l>s.level);
function mutationCard(m,chosen=false,seen=true){return `<article class="dna-card ${seen?'':'undiscovered'}" style="--dna:${m.color}"><span class="dna-emblem">${A.dnaIcon(m.icon)}</span><small>${m.tag}</small><h3>${m.name}</h3><p>${m.description}</p>${chosen?'<span class="dna-card-foot">В ТВОЁМ ГЕНОМЕ ✓</span>':''}</article>`;}
function choice(w){const a=E.prepareAdventure(w.save);return `<div class="eyebrow">ЭВОЛЮЦИЯ ДНК · ${a.mutations.length+1} / 6</div><h2>Измени правила охоты.</h2><p>Выбери одну мутацию на эту жизнь. Она работает сразу и остаётся после рождения в большом мире.</p><div class="dna-choices">${a.offer.map(id=>{const m=E.mutation(id);return `<button class="dna-choice" data-action="mutation-pick" data-id="${id}" aria-label="Выбрать мутацию: ${m.name}">${mutationCard(m)}<span class="dna-choice-footer">ВПИСАТЬ В ГЕНОМ <b>↗</b></span></button>`;}).join('')}</div><div class="dna-current">${a.mutations.length?`Твой геном: ${a.mutations.map(id=>E.mutation(id).name).join(' · ')}`:'Сочетай мутации со способностями своего героя.'}</div>`;}
function mount(w){const hud=$('.hud');if(!hud)return;hud.insertAdjacentHTML('beforeend','<aside class="expedition-hud" id="expedition-hud"></aside>');update(w);}
function update(w){const host=$('#expedition-hud');if(!host)return;const a=E.prepareAdventure(w.save),nest=E.currentNest(w),def=nest&&E.nestDef(nest.id),egg=a.eggs.find(e=>E.eggReady(w,e))||a.eggs[0],pet=a.active&&E.companion(a.active),next=nextPoint(w.save);
 const html=`<button class="dna-journal-button" data-action="journal" aria-label="Геном, яйца и открытия">${A.dnaIcon('book')}<span><b>Атлас жизни</b><small>${a.mutations.length}/6 мутаций${egg?' · '+(E.eggReady(w,egg)?'Яйцо готово!':egg.progress+'/'+egg.target+' охот'):pet?' · '+pet.name:next?' · следующая '+(w.isMicro?'μ':'ур. ')+next:''}</small></span><kbd>C</kbd></button>${a.mutations.length?`<div class="dna-ribbon">${a.mutations.map(id=>{const m=E.mutation(id);return `<button data-action="journal" data-tab="mutations" title="${m.name}: ${m.description}" aria-label="${m.name}" style="color:${m.color}">${A.dnaIcon(m.icon)}</button>`;}).join('')}</div>`:''}${def?`<button class="nest-quest ${def.level>w.save.level*1.55?'danger':''}" data-action="seek-nest"><span class="nest-quest-art">${A.nestPortrait(def.id)}</span><span><small>${nest.state==='cleared'?'ТЫ УЖЕ БЫЛ ЗДЕСЬ':nest.state==='fighting'?'ХРАНИТЕЛЬ ПРОБУДИЛСЯ':'СЕКРЕТ ЭТОГО МИРА'}</small><b>${def.name}</b><em>${nest.state==='cleared'?'Вырасти и поглоти его':`Ур. ${def.level} · ${E.companion(def.kind).egg}`}</em></span><kbd>G</kbd></button>`:w.isMicro&&egg?`<button class="nest-quest" data-action="journal" data-tab="eggs"><span class="nest-quest-art">${A.eggPortrait(egg.kind)}</span><span><small>ПАМЯТЬ ПРОШЛОЙ ЖИЗНИ</small><b>${E.companion(egg.kind).egg}</b><em>Проснётся в большом мире с ур. 10</em></span></button>`:''}`;
 if(host._html!==html){host.innerHTML=html;host._html=html;}
}
function eggs(w,a){return `<p class="atlas-lead">Яйца растут от охоты на подходящую добычу. Вылупление доступно с уровня 10 большого мира. Редкий спутник занимает отдельное место рядом со стаей.</p>${a.eggs.length?`<div class="egg-grid">${a.eggs.map(egg=>{const p=E.companion(egg.kind),ready=w&&E.eggReady(w,egg);return `<article class="egg-card" style="--dna:${p.color}"><div class="egg-art ${ready?'egg-ready':''}">${A.eggPortrait(p.id)}</div><small>РЕДКОЕ ЯЙЦО · ${p.role.toUpperCase()}</small><h3>${p.egg}</h3>${bar(egg.progress,egg.target)}<p>${egg.progress} / ${egg.target} охот${egg.progress>=egg.target&&!ready?' · ждёт ур. 10':''}</p><button class="${ready?'primary':'secondary'}" data-action="hatch-egg" data-id="${egg.id}" ${ready?'':'disabled'}>${ready?'Помочь вылупиться':'Продолжай расти'}</button></article>`;}).join('')}</div>`:'<div class="atlas-empty">'+A.dnaIcon('egg')+'<h3>Первое яйцо ждёт в роще.</h3><p>Победи хранителя гнезда на уровне 8 или вернись к нему, когда станешь сильнее. Найти гнездо: <kbd>G</kbd>.</p></div>'}<h3 class="atlas-subheading">Редкие спутники <span>${a.companions.length} / 3</span></h3><div class="companion-grid">${E.COMPANIONS.map(p=>{const owned=a.companions.find(c=>c.kind===p.id),active=a.active===p.id;return `<article class="companion-card ${owned?'':'undiscovered'}"><div class="companion-art">${A.companionPortrait(p.id)}</div><small>${p.role.toUpperCase()}</small><h3>${p.name}</h3><p>${p.description}</p><span class="bond">${owned?'Связь '+owned.bond+' / 3 · повторное яйцо укрепляет её':'Найди яйцо в гнезде'}</span><button class="${active?'primary':'secondary'}" data-action="rare-pet" data-id="${active?'none':p.id}" ${owned&&w?'':'disabled'}>${active?'С тобой ✓ · отпустить':'Взять с собой'}</button></article>`;}).join('')}</div>`;}
function nests(w,a,profile){return `<p class="atlas-lead">Шесть тайников на пути от рощи до звёзд. Брось вызов хранителю ради яйца. Старое гнездо однажды станет достаточно маленьким, чтобы поглотить его целиком.</p><div class="nest-grid">${E.NESTS.map(n=>{const current=a.nests.find(q=>q.id===n.id),cleared=current?.rewarded,known=profile.nests.includes(n.id);return `<article class="nest-card"><div class="nest-art">${A.nestPortrait(n.id)}</div><div><small>${E.REALMS[n.realm].name.toUpperCase()} · УР. ${fmt(n.level)}</small><h3>${n.name}</h3><p>${n.guardian}<br>Награда: ${E.companion(n.kind).egg}</p><span class="nest-status">${current?.state==='absorbed'?'Поглощено целиком ✓':cleared?'Хранитель побеждён ✓':current?.state==='fighting'?'Хранитель ждёт тебя':known?'Открыто в прошлой жизни':current?'Найдено в этом мире':'Впереди, по пути роста'}</span>${w&&!w.isMicro&&w.realm===n.realm&&current?.state!=='absorbed'?'<button class="secondary" data-action="seek-nest">'+(cleared?'Вернуться к гнезду':'Идти к хранителю')+' ↗</button>':''}</div></article>`;}).join('')}</div>`;}
function discoveries(profile){return `<p class="atlas-lead">Этот атлас сохраняется между жизнями в браузере. Открытый редкий питомец позволяет выбрать его яйцо перед новым путешествием.</p><div class="discovery-stats"><div><b>${profile.seen.length}<small>/ 30</small></b><span>ВИДОВ ПОГЛОЩЕНО</span></div><div><b>${profile.mutations.length}<small>/ 18</small></b><span>МУТАЦИЙ ИСПЫТАНО</span></div><div><b>${profile.companions.length}<small>/ 3</small></b><span>РЕДКИХ СПУТНИКА</span></div><div><b>${profile.heroes.length}<small>/ 4</small></b><span>ГЕРОЯ РОЖДЕНО</span></div></div><h3 class="atlas-subheading">Память о встречах</h3><div class="species-grid">${Array.from({length:30},(_,i)=>{const micro=i<6,tier=micro?0:Math.floor((i-6)/4),slot=micro?i:(i-6)%4,id=(micro?'micro':'world')+':'+tier+':'+slot,seen=profile.seen.includes(id),name=micro?['Питательная молекула','Светящаяся водоросль','Золотая инфузория','Панцирная коловратка','Шипастый микроб','Страж мембраны'][slot]:slot===3?E.BOSSES[tier].name:E.ENEMIES[tier].names[slot];return `<div class="species-card ${seen?'':'undiscovered'}"><div>${seen?A.bank.portrait(micro?'micro-enemies':'enemies-'+tier,slot):A.dnaIcon(micro?'venom':'nest')}</div><span>${seen?name:micro?'Неизвестная жизнь':E.REALMS[tier].name}</span><small>${seen?'ИЗУЧЕНО ✓':'ЕЩЁ НЕ ВСТРЕЧЕНО'}</small></div>`;}).join('')}</div>`;}
function journal(w,profile,tab='mutations'){const a=w?E.prepareAdventure(w.save):{mutations:[],eggs:[],companions:[],nests:[],active:null};const next=w&&nextPoint(w.save);return `<div class="collection-header"><div><div class="eyebrow">КАЖДАЯ ЖИЗНЬ ОСТАВЛЯЕТ СЛЕД</div><h2>Атлас жизни</h2></div><button class="icon-button" data-action="close-journal" aria-label="Закрыть атлас">✕</button></div><nav class="atlas-tabs">${[['mutations','Геном'],['eggs','Яйца и спутники'],['nests','Гнёзда'],['discoveries','Открытия']].map(([id,label])=>`<button data-action="journal-tab" data-tab="${id}" aria-pressed="${tab===id}" class="${tab===id?'active':''}">${label}</button>`).join('')}</nav>${tab==='eggs'?eggs(w,a):tab==='nests'?nests(w,a,profile):tab==='discoveries'?discoveries(profile):`<p class="atlas-lead">${w?`Твой геном: ${a.mutations.length} / 6 мутаций. ${next?'Следующий выбор — '+(w.isMicro?'μ':'ур. ')+next+'.':'Продолжай путь с выбранными способностями.'}`:'Начни новую жизнь, чтобы собрать свой геном.'} На каждом выборе доступны три варианта. Мутации разных героев создают разные сочетания.</p>${a.mutations.length?`<div class="mutation-library current-build">${a.mutations.map(id=>mutationCard(E.mutation(id),true)).join('')}</div>`:''}<h3 class="atlas-subheading">Возможности эволюции <span>${profile.mutations.length} / 18 испытано</span></h3><div class="mutation-library">${E.MUTATIONS.map(m=>`<div>${mutationCard(m,false,profile.mutations.includes(m.id)||a.mutations.includes(m.id))}<small class="library-group">${m.group==='common'?'Любой герой':E.hero(m.group).name}${profile.mutations.includes(m.id)?' · открыто ✓':''}</small></div>`).join('')}</div>`}`;}
function hatchReveal(p){const def=E.companion(p.kind);return `<div class="eyebrow">${p.first?'НОВАЯ ЖИЗНЬ В ТВОЕЙ СТАЕ':'ВАША СВЯЗЬ СТАЛА СИЛЬНЕЕ'}</div><div class="hatch-art">${A.companionPortrait(p.kind)}</div><h2>${def.name}${p.first?' проснулся!':' · связь '+p.bond}</h2><p><b>${def.role}.</b> ${def.description}</p><p>В следующей жизни ты сможешь выбрать его яйцо. Этот спутник остаётся в твоём атласе открытий.</p><button class="primary" data-action="hatch-done">Продолжить охоту ↗</button>`;}
function heritage(profile,selected){if(!profile.companions.length)return '';return `<div class="heritage"><div><small>ПОДАРОК ИЗ ПРОШЛОЙ ЖИЗНИ</small><b>Какое яйцо взять с собой?</b></div><div class="heritage-options">${profile.companions.map(id=>`<button class="${id===selected?'selected':''}" data-action="inherit-egg" data-id="${id}" aria-pressed="${id===selected}">${A.eggPortrait(id)}<span>${E.companion(id).egg}</span></button>`).join('')}</div></div>`;}
window.ExpeditionUI={choice,mount,update,journal,hatchReveal,heritage};
})();
