(() => {
'use strict';
const E=window.Evolution,A=window.EvolutionArt,X=window.ExpeditionUI,$=s=>document.querySelector(s);
const stories={shelter:{title:'Когда лист был целым домом',text:'Ты спрятался под листом. Хищник ходил рядом, но не мог достать тебя.',after:'Первое укрытие найдено',icon:'shield'},predator:{title:'Охотник стал добычей',text:'Шорох пугал тебя у берега. Теперь он стал частью твоей силы.',after:'Тот самый хищник поглощён',icon:'venom'},den:{title:'Его дом помещается в твоих лапах',text:'Корни разлетелись. Там, где жил твой первый враг, осталось маленькое пятно.',after:'Логово разрушено · получено лесное яйцо',icon:'nest'},pond:{title:'Твой первый мир — одна капля',text:'Когда-то этот пруд казался бесконечным. Теперь ты поглотил его целиком.',after:'Жемчужина начала · +5% опыта',icon:'egg'}};
function journal(w,profile){const h=w?E.prepareHabitat(w.save):null,done=id=>h?({shelter:h.sheltered,predator:h.predator==='eaten',den:h.den==='broken',pond:h.pond==='absorbed'})[id]:profile.memories?.includes(id);return `<div class="collection-header"><div><div class="eyebrow">МИР ПОМНИТ, КАКИМ МАЛЕНЬКИМ ТЫ БЫЛ</div><h2>Пруд первой капли</h2></div><button class="icon-button" data-action="close-journal" aria-label="Закрыть атлас">✕</button></div><nav class="atlas-tabs"><button data-action="journal-tab" data-tab="mutations">Геном</button><button data-action="journal-tab" data-tab="eggs">Яйца и спутники</button><button data-action="journal-tab" data-tab="discoveries">Открытия</button><button class="active" data-action="journal-tab" data-tab="home" aria-pressed="true">Родной мир</button></nav><p class="atlas-lead">Микромир — жизнь внутри капли этого пруда. После рождения ты выйдешь на его берег. Лист, хищник и логово останутся на своих местах; меняться будет твой размер.</p><div class="home-chronicle">${Object.entries(stories).map(([id,s],i)=>`<article class="home-memory ${done(id)?'remembered':''}"><div class="memory-art">${A.homePortrait(id)}</div><div><small>0${i+1} · ${done(id)?'ТВОЯ ИСТОРИЯ':'ВПЕРЕДИ'}</small><h3>${s.title}</h3><p>${s.text}</p><span>${done(id)?s.after:id==='shelter'?'Начало большого мира · выбор добычи раскрывает тебя':id==='predator'?'Шорох · уровень 14':id==='den'?'Уровень 35 · после победы над Шорохом':'Уровень 180 · после разрушения логова'}</span></div></article>`).join('')}</div>${w&&!w.isMicro&&h.pond!=='absorbed'?`<button class="primary home-return" data-action="home-go">${E.homeObjective(w).action} <kbd>V</kbd></button>`:''}<p class="atlas-lead home-footnote">Изменения сохраняются в этой жизни. В новой вселенной место оживёт снова, а воспоминания останутся в атласе. В любой момент можно остановиться и продолжить позже.</p>`;}
const oldJournal=X.journal;X.journal=(w,profile,tab)=>tab==='home'?journal(w,profile):oldJournal(w,profile,tab).replace('</nav>','<button data-action="journal-tab" data-tab="home">Родной мир</button></nav>');
const oldUpdate=X.update;X.update=function(w){oldUpdate(w);const host=$('#expedition-hud');if(!host)return;let card=$('#home-card');if(!card){host.insertAdjacentHTML('beforeend','<section class="home-card" id="home-card"></section>');card=$('#home-card');}const o=E.homeObjective(w),h=E.prepareHabitat(w.save),q=w.habitatChannel,done=[h.sheltered,h.predator==='eaten',h.den==='broken',h.pond==='absorbed'];
 const html=`<button class="home-card-title" data-action="journal" data-tab="home">${A.dnaIcon('nest')}<span>ТВОЙ ПЕРВЫЙ МИР</span><b>↗</b></button><div class="home-steps">${['Лист','Хищник','Логово','Пруд'].map((t,i)=>`<span class="${done[i]?'done':''}"><i>${done[i]?'✓':i+1}</i>${t}</span>`).join('')}</div><strong>${q?(q.kind==='pond'?'Поглощение пруда…':'Корни трещат…'):o.name}</strong><p>${q?'Движение отменяет поглощение.':o.description}</p>${q?`<div class="dna-progress"><i style="width:${Math.floor(q.elapsed/q.duration*100)}%"></i></div>`:`<button class="home-card-action" data-action="${w.isMicro||o.id==='complete'?'journal':'home-go'}" data-tab="home">${o.action}<kbd>V</kbd></button>`}`;
 if(card._html!==html){card.innerHTML=html;card._html=html;}card.classList.toggle('safe',E.inShelter(w));
};
const oldMount=X.mount;X.mount=w=>{oldMount(w);X.update(w);};
function showMoment(id){const s=stories[id];if(!s)return;let el=$('#home-moment');if(!el){el=document.createElement('div');el.id='home-moment';el.setAttribute('role','status');document.body.append(el);}el.hidden=false;el.innerHTML=`<div>${A.homePortrait(id)}</div><span><small>ТЫ ВЫРОС. МИР ЗАПОМНИЛ.</small><b>${s.title}</b><em>${s.after}</em></span>`;el.classList.add('visible');clearTimeout(showMoment.timer);showMoment.timer=setTimeout(()=>{el.classList.remove('visible');el.hidden=true;},5600);}
window.LivingUI={showMoment};
})();
